#
OBJFILES= m_strings.o
MODFILES=$(OBJFILES:.o=)

#------------------------------
MK=$(FLIB_ROOT)/lib.mk
include $(MK)
#------------------------------

FFLAGS=$(FFLAGS_CHECK)

clean:
	rm -f *.o *.$(MOD_EXT)

