#
OBJFILES= m_stmw.o m_cmlw.o flib_cml.o
MODFILES=$(OBJFILES:.o=)

#------------------------------
MK=$(FLIB_ROOT)/lib.mk
include $(MK)
#------------------------------

clean:
	rm -f *.o *.$(MOD_EXT)

